const colors = require('tailwindcss/colors');
module.exports = {
  content: [
    './App.{js,jsx,ts,tsx}',
    './components/**/*.{js,jsx,ts,tsx}',
    './screens/*.{js,jsx,ts,tsx}',
  ],
  theme: {
    colors: {
      white10: '#ffffff10',
      white20: '#ffffff20',
      white30: '#ffffff30',
      white40: '#ffffff40',
      white50: '#ffffff50',
      white60: '#ffffff60',
      white70: '#ffffff70',
      white80: '#ffffff80',
      white90: '#ffffff90',
      noteGrey: {
        300: '#929292',
        500: '#6d6d6d',
        900: '#222222',
      },
      //defaults
      black: '#000000',
      white: '#ffffff',
      transparent: 'transparent',
      current: 'currentColor' /* ??? */,
      slate: colors.slate,
      gray: colors.gray,
      zinc: colors.zinc,
      neutral: colors.neutral,
      stone: colors.stone,
      red: colors.red,
      orange: colors.orange,
      amber: colors.amber,
      yellow: colors.yellow,
      lime: colors.lime,
      green: colors.green,
      emerald: colors.emerald,
      cyan: colors.cyan,
      sky: colors.sky,
      blue: colors.blue,
      indigo: colors.indigo,
      violet: colors.violet,
      purple: colors.purple,
      fuchsia: colors.fuchsia,
      pink: colors.pink,
      rose: colors.rose,
    },
    extend: {
      fontFamily: {
        // sans: ['Montserrat-Bold'],
      },
    },
  },
  plugins: [],
};
